name: Zangar

on:
  push:
    branches: [ asli ]
  pull_request:
    branches: [ asli ]

jobs:
  ic:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Lancer les exemples
        uses: actions-rs/cargo@v1
        with:
          command: run
